[versions]
revanced-patcher = "22.0.0"
# Tracking https://github.com/google/smali/issues/64.
#noinspection GradleDependency
smali = "3.0.5"
revanced-patches = "6.0.0-dev.4"

[libraries]
revanced-patches = { module = "app.revanced:patches", version.ref = "revanced-patches" }

[plugins]
android-library = { id = "com.android.library" }