[versions]
revanced-patcher = "22.0.0"
# Tracking https://github.com/google/smali/issues/64.
#noinspection GradleDependency
smali = "3.0.5"
revanced-patches = "5.50.3-dev.3-local"

[libraries]
revanced-patches = { module = "revanced-patches:patches", version.ref = "revanced-patches" }

[plugins]
android-library = { id = "com.android.library" }